/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import entidades.Licencia;
import entidades.Persona;
import entidades.Placa;
import entidades.Tramites;
import interfaces.iTramiteDAO;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import persistencia.TramiteDAO;

/**
 * Interfaz gráfica para la consulta acorde a una persona seleccionada.
 *
 * @author Jesus Rodrigo Villegas Arguelles 261186
 * @author Alejandro Rodríguez Lugo 251622
 * @author Héctor Javier Alonso Zaragoza 252039
 */
public class ConsultarPersonaForm extends javax.swing.JDialog {

    /**
     * Inicializa los valores a utilizar en la consulta.
     */
    private Persona personaSeleccionada;
    private JTable tablaHistorial;
    iTramiteDAO t = new TramiteDAO();

    /**
     * Creates new form ConsultarPersonaForm
     */
    public ConsultarPersonaForm(java.awt.Frame parent, boolean modal, Persona persona) {
        super(parent, modal);
        initComponents();
        this.personaSeleccionada = persona;
        llenarTabla();
        for (int i = 0; i < jTable1.getColumnCount(); i++) {
            Class<?> colClass = jTable1.getColumnClass(i);
            jTable1.setDefaultEditor(colClass, null);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Tipo de trámite", "Costo", "Fecha", "Persona"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Trámite de persona");
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void llenarTabla() {
        List<Tramites> listaEventos = t.ConsultarTodos();
        DefaultTableModel modelo = new DefaultTableModel();
        String[] columnas = {"Id", "Tipo de trámite", "Costo", "Fecha del trámite", "Persona"};
        modelo.setColumnIdentifiers(columnas);
        if (listaEventos != null) {
            for (Tramites tramite : listaEventos) {
                if (tramite.getPersona().getId().equals(personaSeleccionada.getId())) {
                    String fecha = "";
                    if (tramite instanceof Licencia) {
                        Licencia licencia = (Licencia) tramite;
                        fecha = licencia.getFechaExpedicion().toString();
                    } else if (tramite instanceof Placa) {
                        Placa placa = (Placa) tramite;
                        fecha = placa.getFechaEmision().toString();
                    }
                    Object[] registros = {tramite.getId(), tramite.getClass().getSimpleName(), tramite.getCosto(), fecha, tramite.getPersona().getNombre()
                    };
                    modelo.addRow(registros);
                }
            }
        }
        jTable1.setModel(modelo);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
