/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import javax.swing.JFrame;

/**
 * Interfaz gráfica para escoger la placa acorde al carro.
 *
 * @author Jesus Rodrigo Villegas Arguelles 261186
 * @author Alejandro Rodríguez Lugo 251622
 * @author Héctor Javier Alonso Zaragoza 252039
 */
public class PlacaForm extends javax.swing.JFrame {

    /**
     * Creates new form PlacaForm
     */
    public PlacaForm() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPlacaUsado = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnPlacaNuevo = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPlacaUsado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPlacaUsado.setText("Solicitar placa para automóvil usado");
        btnPlacaUsado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlacaUsadoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Solicitar placa");

        btnPlacaNuevo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPlacaNuevo.setText("Solicitar placa para automóvil nuevo");
        btnPlacaNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlacaNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPlacaUsado, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPlacaNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(btnPlacaNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btnPlacaUsado, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlacaUsadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlacaUsadoActionPerformed
        // TODO add your handling code here:
        PlacasUsadosForm pcu = new PlacasUsadosForm(this, true);
        pcu.setVisible(true);
        pcu.setLocationRelativeTo(this);
    }//GEN-LAST:event_btnPlacaUsadoActionPerformed

    private void btnPlacaNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlacaNuevoActionPerformed
        // TODO add your handling code here:
        PlacasNuevasForm pcn = new PlacasNuevasForm(this, true);
        pcn.setVisible(true);
        pcn.setLocationRelativeTo(this);
    }//GEN-LAST:event_btnPlacaNuevoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnPlacaNuevo;
    private javax.swing.JButton btnPlacaUsado;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
