/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import entidades.Automovil;
import entidades.Licencia;
import entidades.Persona;
import entidades.Placa;
import entidades.Vehiculo;
import interfaces.iAutomovilDAO;
import interfaces.iPersonasDAO;
import interfaces.iPlacaDAO;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import persistencia.AutomovilDAO;
import persistencia.PersonasDAO;
import persistencia.PlacaDAO;

/**
 * Interfaz gráfica para generar una placa a un vehiculo usado.
 *
 * @author Jesus Rodrigo Villegas Arguelles 261186
 * @author Alejandro Rodríguez Lugo 251622
 * @author Héctor Javier Alonso Zaragoza 252039
 */
public class PlacasUsadosForm extends javax.swing.JDialog {

    /**
     * Inicializa los valores para generar una placa para un vehiculo usado.
     */
    iAutomovilDAO a = new AutomovilDAO();
    iPlacaDAO placa = new PlacaDAO();
    iPersonasDAO p = new PersonasDAO();
    private List<Persona> listaPersonas;

    /**
     * Creates new form PlacasUsadosForm
     */
    public PlacasUsadosForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargarAutos();
        cargarPersonasConLicenciaVigente();
        jTextField1.setEditable(false);
        jTextField2.setEditable(false);
        jTextField3.setEditable(false);
        jTextField4.setEditable(false);
        jTextField5.setEditable(false);
        jTextField6.setEditable(false);
        datePicker1.setEnabled(false);
        jTextField7.setEditable(false);
        datePicker2.setEnabled(false);
        jTextField9.setEditable(false);
        jTextField10.setEditable(false);
        datePicker2.setDate(LocalDate.now());
        jComboBox2.addActionListener(e -> actualizarAuto());
        jComboBox1.addActionListener(e -> actualizarEstado());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        datePicker1 = new com.github.lgooddatepicker.components.DatePicker();
        btnRegistrarPlaca = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        datePicker2 = new com.github.lgooddatepicker.components.DatePicker();
        jLabel15 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        btnAtras = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Realizar trámite para vehículo usado");
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N

        jLabel2.setText("Placas del vehículo");

        jLabel3.setText("Número de serie");

        jLabel4.setText("Marca");

        jLabel5.setText("Línea");

        jLabel6.setText("Color");

        jLabel7.setText("Modelo");

        jLabel8.setText("Tipo de vehículo");

        jLabel9.setText("Costo ($)");

        jTextField6.setText("1000");
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jLabel10.setText("Fecha de emisión");

        btnRegistrarPlaca.setText("Registar placa");
        btnRegistrarPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPlacaActionPerformed(evt);
            }
        });

        jLabel11.setText("Seleccionar persona");

        jLabel12.setText("con licencia vigente");

        jLabel13.setText("Estado de placa ");

        jTextField7.setToolTipText("");

        jLabel14.setText("Fecha de recepción");

        jLabel15.setText("Número de placa nuevo");

        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        jLabel16.setText("Número de puertas");

        jLabel17.setText("Tipo de motor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(154, 154, 154)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(202, 202, 202)
                                .addComponent(datePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel2))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jComboBox1, 0, 153, Short.MAX_VALUE)
                                                .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jTextField8)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel6)
                                                .addComponent(jLabel7)
                                                .addComponent(jLabel16)
                                                .addComponent(jLabel17))
                                            .addGap(100, 100, 100)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jTextField1)
                                                .addComponent(jTextField2)
                                                .addComponent(jTextField3)
                                                .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                                                .addComponent(jTextField9)
                                                .addComponent(jTextField10))))
                                    .addComponent(jLabel15))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel14))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(datePicker2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jTextField7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                                .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.LEADING))))))
                            .addComponent(jLabel10)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAtras)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRegistrarPlaca)
                                .addGap(1, 1, 1))
                            .addComponent(jLabel1))))
                .addGap(33, 46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(datePicker2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel15))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(datePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarPlaca)
                    .addComponent(btnAtras))
                .addGap(12, 12, 12))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void btnRegistrarPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPlacaActionPerformed
        // TODO add your handling code here:
        try {
            Automovil auto = (Automovil) jComboBox2.getSelectedItem();
            Placa placaU = (Placa) jComboBox1.getSelectedItem();
            String numeroPlaca = jTextField8.getText();
            String marca = jTextField2.getText();
            String linea = jTextField3.getText();
            String color = jTextField1.getText();
            String modelo = jTextField4.getText();
            LocalDate fechaEmision = datePicker1.getDate();
            LocalDate fechaRecepcion = datePicker2.getDate();
            String estado = jTextField7.getText();
            Persona personaSeleccionada = (Persona) jComboBox3.getSelectedItem();
            if (auto == null || placaU == null || marca.isEmpty() || linea.isEmpty() || color.isEmpty() || modelo.isEmpty() || fechaEmision == null || estado.isEmpty() || fechaRecepcion == null) {
                JOptionPane.showMessageDialog(this, "No puede haber datos vacíos.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (!numeroPlaca.matches("^[A-Z]{3}-\\d{3}$")) {
                JOptionPane.showMessageDialog(this, "El formato de la placa es inválido.\nDebe ser 3 letras mayúsculas, un guión y 3 números (ej. AAA-111).", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            Placa placaExistente = placa.ConsultarPorNumPlaca(numeroPlaca);
            if (placaExistente != null) {
                JOptionPane.showMessageDialog(this, "No se puede registrar una placa con el mismo número.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (!placaU.getEstado().matches("Activa")) {
                JOptionPane.showMessageDialog(this, "No se puede registrar una placa nueva sobre una placa ya desactivada.\nEscoge la placa activa.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (!placaU.getPersona().getId().equals(personaSeleccionada.getId())) {
                JOptionPane.showMessageDialog(this, "La placa no le pertenece a la persona seleccionada.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            Placa placaUsado = new Placa();
            placaUsado.setFechaEmision(LocalDate.now());
            placaUsado.setEstado("Activa");
            placaUsado.setNumeroPlaca(numeroPlaca);
            placaUsado.setCosto(Integer.parseInt(jTextField6.getText()));
            placaUsado.setVehiculo(auto);
            placaUsado.setPersona(personaSeleccionada);
            if (placa.Agregar(placaUsado) != true) {
                JOptionPane.showMessageDialog(this, "No se puede registrar la placa.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            } else {
                placaU.setFechaRecepcion(fechaRecepcion);
                placaU.setEstado("Desactiva");
                placa.Actualizar(placaU.getId(), placaU);
                actualizarAuto();
                JOptionPane.showMessageDialog(this, "Placa nueva registrada.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "No puede haber datos vacíos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRegistrarPlacaActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void cargarAutos() {
        jComboBox2.removeAllItems();
        List<Automovil> autos = new ArrayList<>();
        try {
            autos = a.ConsultarTodos();
        } catch (Exception ex) {
            Logger.getLogger(LicenciasForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (Automovil at : autos) {
            jComboBox2.addItem(at);
        }
    }

    private void actualizarAuto() {
        Automovil auto = (Automovil) jComboBox2.getSelectedItem();
        if (auto == null) {
            return;
        }
        jTextField2.setText(auto.getMarca());
        jTextField3.setText(auto.getLinea());
        jComboBox1.removeAllItems();
        List<Placa> placas = new ArrayList<>();
        try {
            placas = placa.ConsultarTodos();
        } catch (Exception ex) {
            Logger.getLogger(LicenciasForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (Placa pla : placas) {
            if (auto.getNumeroSerie().matches(pla.getVehiculo().getNumeroSerie())) {
                jComboBox1.addItem(pla);
            }
        }
        jTextField1.setText(auto.getColor());
        jTextField4.setText(auto.getModelo());
        jTextField5.setText(auto.getTipoVehiculo());
        Placa placaSeleccionada = (Placa) jComboBox1.getSelectedItem();
        if (placaSeleccionada == null) {
            return;
        }
        datePicker1.setDate(placaSeleccionada.getFechaEmision());
        jTextField7.setText(placaSeleccionada.getEstado());
        jTextField9.setText(auto.getNumeroPuertas());
        jTextField10.setText(auto.getTipoMotor());
    }

    private void actualizarEstado() {
        Placa estadoPlaca = (Placa) jComboBox1.getSelectedItem();
        if (estadoPlaca == null) {
            return;
        }
        jTextField7.setText(estadoPlaca.getEstado());
    }

    private void cargarPersonasConLicenciaVigente() {
        jComboBox1.removeAllItems();
        List<Persona> pers = new ArrayList<>();
        try {
            pers = p.ConsultarTodos();
        } catch (Exception ex) {
            Logger.getLogger(LicenciasForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        Set<Long> idsAgregados = new HashSet<>();
        LocalDate hoy = LocalDate.now();
        for (Persona persona : pers) {
            if (!persona.getTramites().isEmpty()) {
                boolean tieneVigente = persona.getTramites().stream().anyMatch(tramite -> {
                    if (tramite instanceof Licencia) {
                        Licencia lic = (Licencia) tramite;
                        LocalDate fechaVigencia = lic.getFechaExpedicion().plusYears(lic.getVigencia());
                        return fechaVigencia.isAfter(hoy) || fechaVigencia.isEqual(hoy);
                    }
                    return false;
                });

                if (tieneVigente && !idsAgregados.contains(persona.getId())) {
                    jComboBox3.addItem(persona);
                    idsAgregados.add(persona.getId());
                }
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnRegistrarPlaca;
    private com.github.lgooddatepicker.components.DatePicker datePicker1;
    private com.github.lgooddatepicker.components.DatePicker datePicker2;
    private javax.swing.JComboBox<Placa> jComboBox1;
    private javax.swing.JComboBox<Automovil> jComboBox2;
    private javax.swing.JComboBox<Persona> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
