/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import entidades.Automovil;
import entidades.Licencia;
import entidades.Persona;
import entidades.Placa;
import interfaces.*;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import persistencia.AutomovilDAO;
import persistencia.PersonasDAO;
import persistencia.PlacaDAO;

/**
 * Interfaz gráfica para generar una placa a un vehiculo nuevo.
 *
 * @author Jesus Rodrigo Villegas Arguelles 261186
 * @author Alejandro Rodríguez Lugo 251622
 * @author Héctor Javier Alonso Zaragoza 252039
 */
public class PlacasNuevasForm extends javax.swing.JDialog {

    /**
     * Inicializa los valores para generar una placa para un vehiculo nuevo.
     */
    iPersonasDAO p = new PersonasDAO();
    private List<Persona> listaPersonas;
    iPlacaDAO placa = new PlacaDAO();
    iAutomovilDAO a = new AutomovilDAO();

    /**
     * Creates new form PlacasNuevasForm
     */
    public PlacasNuevasForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargarPersonasConLicenciaVigente();
        datePicker1.setEnabled(false);
        datePicker1.setDate(LocalDate.now());
        jTextField6.setEditable(false);
        jTextField8.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        btnGenerarPlaca = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        datePicker1 = new com.github.lgooddatepicker.components.DatePicker();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        btnAtras = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Realizar trámite para vehículo nuevo");
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N

        jLabel2.setText("Número de serie ");

        jLabel3.setText("Marca");

        jLabel4.setText("Línea");

        jLabel5.setText("Color");

        jLabel6.setText("Modelo");

        btnGenerarPlaca.setText("Generar placa");
        btnGenerarPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarPlacaActionPerformed(evt);
            }
        });

        jLabel7.setText("Fecha de emisión");

        jLabel8.setText("Seleccionar persona");

        jLabel9.setText("con licencia vigente");

        jLabel10.setText("Costo ($)");

        jTextField6.setText("1500");
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jLabel11.setText("Número de placa");

        jLabel12.setText("Tipo vehiculo");

        jTextField8.setText("Automóvil");

        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        jLabel13.setText("Número de puertas");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "4", "2" }));

        jLabel14.setText("Tipo de motor");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Combustión", "Híbrido", "Eléctrico" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel10)
                                .addComponent(jLabel11)
                                .addComponent(jLabel13)
                                .addComponent(jLabel14))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAtras)
                                .addGap(43, 43, 43)))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextField2)
                                        .addComponent(jTextField3)
                                        .addComponent(jTextField4)
                                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(74, 74, 74)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(33, 33, 33)
                                        .addComponent(datePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel9)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel12))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(57, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnGenerarPlaca)
                .addGap(97, 97, 97))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(datePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerarPlaca)
                    .addComponent(btnAtras))
                .addGap(27, 27, 27))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarPlacaActionPerformed
        // TODO add your handling code here:
        try {
            String numPlaca = jTextField7.getText();
            String numSerie = jTextField1.getText();
            String marca = jTextField2.getText();
            String linea = jTextField3.getText();
            String color = jTextField4.getText();
            String modelo = jTextField5.getText();
            String tipoVehiculo = jTextField8.getText();
            LocalDate fechaEmision = datePicker1.getDate();
            String numPuertas = (String) jComboBox2.getSelectedItem();
            String tipoMotor = (String) jComboBox3.getSelectedItem();
            Persona personaSeleccionada = (Persona) jComboBox1.getSelectedItem();
            if (numPlaca.isEmpty() || numSerie.isEmpty() || marca.isEmpty() || linea.isEmpty() || color.isEmpty() || modelo.isEmpty() || fechaEmision == null || tipoVehiculo.isEmpty() || numPuertas.isEmpty() || tipoMotor.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No puede haber datos vacíos.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (!numPlaca.matches("^[A-Z]{3}-\\d{3}$")) {
                JOptionPane.showMessageDialog(this, "El formato de la placa es inválido.\nDebe ser 3 letras mayúsculas, un guión y 3 números (ej. AAA-111).", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (!numSerie.matches("^[A-Z]{3}-\\d{3}$")) {
                JOptionPane.showMessageDialog(this, "El formato del N de serie es inválido.\nDebe ser 3 letras mayúsculas, un guión y 3 números (ej. AAA-111).", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            Automovil autoExistente = a.ConsultarPorNumSerie(numSerie);
            if (autoExistente != null) {
                JOptionPane.showMessageDialog(this, "No se puede registrar un carro con el mismo número de serie.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            Placa placaExistente = placa.ConsultarPorNumPlaca(numPlaca);
            if (placaExistente != null) {
                JOptionPane.showMessageDialog(this, "No se puede registrar una placa con el mismo número.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            Placa placaGenerada = new Placa();
            Automovil auto = new Automovil();
            auto.setNumeroSerie(numSerie);
            auto.setModelo(modelo);
            auto.setMarca(marca);
            auto.setLinea(linea);
            auto.setColor(color);
            auto.setNumeroPuertas(numPuertas);
            auto.setTipoMotor(tipoMotor);
            auto.setTipoVehiculo(tipoVehiculo);
            if (a.Agregar(auto) != true) {
                JOptionPane.showMessageDialog(this, "No se pudo registrar el carro.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            } else {
            }
            placaGenerada.setNumeroPlaca(numPlaca);
            placaGenerada.setCosto(Integer.parseInt(jTextField6.getText()));
            placaGenerada.setFechaEmision(fechaEmision);
            placaGenerada.setPersona(personaSeleccionada);
            placaGenerada.setVehiculo(auto);
            placaGenerada.setEstado("Activa");
            if (placa.Agregar(placaGenerada) != true) {
                JOptionPane.showMessageDialog(this, "No se pudo generar la placa.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            } else {
                JOptionPane.showMessageDialog(this, "Placa generada correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                limpiarTabla();
                return;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "No puede haber datos vacíos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGenerarPlacaActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void cargarPersonasConLicenciaVigente() {
        jComboBox1.removeAllItems();
        List<Persona> pers = new ArrayList<>();
        try {
            pers = p.ConsultarTodos();
        } catch (Exception ex) {
            Logger.getLogger(LicenciasForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        Set<Long> idsAgregados = new HashSet<>();
        LocalDate hoy = LocalDate.now();
        for (Persona persona : pers) {
            if (!persona.getTramites().isEmpty()) {
                boolean tieneVigente = persona.getTramites().stream().anyMatch(tramite -> {
                    if (tramite instanceof Licencia) {
                        Licencia lic = (Licencia) tramite;
                        LocalDate fechaVigencia = lic.getFechaExpedicion().plusYears(lic.getVigencia());
                        return fechaVigencia.isAfter(hoy) || fechaVigencia.isEqual(hoy);
                    }
                    return false;
                });

                if (tieneVigente && !idsAgregados.contains(persona.getId())) {
                    jComboBox1.addItem(persona);
                    idsAgregados.add(persona.getId());
                }
            }
        }
    }

    private void limpiarTabla() {
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField7.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnGenerarPlaca;
    private com.github.lgooddatepicker.components.DatePicker datePicker1;
    private javax.swing.JComboBox<Persona> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
