/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import com.mysql.cj.Session;
import entidades.Persona;
import interfaces.iPersonasDAO;
import java.time.LocalDate;
import java.time.Month;
import java.util.List;
import javax.swing.JOptionPane;
import persistencia.PersonasDAO;
import encriptador.Encriptador;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.SwingUtilities;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.view.JasperViewer;

/**
 * Interfaz gráfica para el menú principal.
 *
 * @author Jesus Rodrigo Villegas Arguelles 261186
 * @author Alejandro Rodríguez Lugo 251622
 * @author Héctor Javier Alonso Zaragoza 252039
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Inicializa las personas para generar un inserción masiva.
     */
    iPersonasDAO personaDAO = new PersonasDAO();

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        btnInsercion.setIcon(new javax.swing.ImageIcon("imagenes/gente.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnInsercion = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnLicencias = new javax.swing.JButton();
        btnPlaca = new javax.swing.JButton();
        btnConsultas = new javax.swing.JButton();
        btnReporte = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 52)); // NOI18N
        jLabel1.setText("Agencia fiscal");

        btnInsercion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsercionActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Inserción masiva de \npersonas");

        btnLicencias.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnLicencias.setText("Solicitar licencia");
        btnLicencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLicenciasActionPerformed(evt);
            }
        });

        btnPlaca.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnPlaca.setText("Solicitar placa");
        btnPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlacaActionPerformed(evt);
            }
        });

        btnConsultas.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnConsultas.setText("Consulta de trámite");
        btnConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultasActionPerformed(evt);
            }
        });

        btnReporte.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnReporte.setText("Generar reporte");
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(194, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnInsercion, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLicencias, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(174, 174, 174))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addComponent(btnLicencias, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(btnInsercion, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(24, 24, 24))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLicenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLicenciasActionPerformed
        // TODO add your handling code here:
        LicenciasForm licencia = new LicenciasForm(this, true);
        licencia.setVisible(true);
    }//GEN-LAST:event_btnLicenciasActionPerformed

    private void btnInsercionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsercionActionPerformed
        // TODO add your handling code here:
        List<Persona> personas = personaDAO.ConsultarTodos();
        if (personas != null && !personas.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ya se realizo la inserción masiva.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String[] nombres = {"Angel Campas Moreno", "Mario Osuna Cuen", "Sebastian Diaz Zaragoza", "Jordan Barret Alonso", "Elva Gutierrez Medina", "Aarón Inzunza Lira", "Jesus Ramirez Valenzuela",
            "Maximo Jimenez Gonzalez", "Rafael Mendonza Godinez", "Guillemo Salazar Ramirez", "Raul Montoya Navarro", "Paul Coeto Merino", "Sinai Alpuche Gaxiola", "Luisa Robles Jimenez",
            "Adrian Masias Estrada", "Saul Apodaca Baldenegro", "Luciano Barceló Murrieta", "Michel Bollinger Morgana", "Sebastian Galvez Gonzalez", "Lepier Caro Castro", "Daniel Vega Coronado"};
        LocalDate[] fechasNacimiento = {LocalDate.of(1992, 5, 14), LocalDate.of(1988, 9, 22), LocalDate.of(1996, 11, 3), LocalDate.of(1999, 7, 18), LocalDate.of(1990, 3, 8), LocalDate.of(2001, 6, 25),
            LocalDate.of(1995, 12, 12), LocalDate.of(1998, 8, 4), LocalDate.of(1989, 4, 27), LocalDate.of(1993, 1, 15), LocalDate.of(1997, 10, 5), LocalDate.of(2000, 2, 20), LocalDate.of(1991, 9, 9),
            LocalDate.of(1994, 11, 29), LocalDate.of(1987, 7, 6), LocalDate.of(1999, 5, 30), LocalDate.of(2002, 3, 10), LocalDate.of(1990, 8, 16), LocalDate.of(1998, 12, 24), LocalDate.of(2003, 4, 11), LocalDate.of(1995, 10, 2)};
        String[] rfcs = {"CAMÁ920514HSL", "OSCM880922HSL", "DIZS961103HSL", "BAAJ990718HSL", "GUME900308MSL", "INLA010625HSL", "RAVJ951212HSL", "JIGM980804HSL", "MEGR890427HSL", "SARG930115HSL", "MONR971005HSL", "COMP000220HSL", "ALGS910909MSL",
            "ROJL941129MSL", "MAEA870706HSL", "APBS990530HSL", "BAML020310HSL", "BOMM900816MSL", "GAGS981224HSL", "CACL030411HSL", "VECD951002HSL"
        };

        int[] telefonos = {644345789, 644398456, 644512345, 644478912, 644334567, 644291034, 662443221, 662509876, 662376543, 662498765, 662467890, 662356781, 662423567, 662401234,
            662490876, 644378901, 644465432, 644487654, 644432198, 662498321, 644410987};
        int contador = 0;
        Set<String> rfcSet = new HashSet<>();
        for (String rfc : rfcs) {
            if (!rfcSet.add(rfc)) {
                JOptionPane.showMessageDialog(this, "Hay RFCs repetidos en la inserción masiva.\nRFC duplicado: " + rfc, "Error", JOptionPane.ERROR_MESSAGE);
                return;
            } else if (rfc.length() > 13) {
                JOptionPane.showMessageDialog(this, "Hay RFC con longitud mayor a 13.\nRFC: " + rfc, "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        for (int i = 1; i <= nombres.length; i++) {
            try {
                Persona persona = new Persona();
                persona.setNombre(nombres[i]);
                persona.setRFC(rfcs[i]);
                String telefonoEncriptado = Encriptador.encriptar(String.valueOf(telefonos[i]));
                persona.setTelefono(telefonoEncriptado);
                persona.setFechaNacimiento(fechasNacimiento[i]);
                personaDAO.Agregar(persona);
                contador++;
            } catch (Exception e) {
            }
        }
        JOptionPane.showMessageDialog(this, "Inserción masiva de 20 personas realizada.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnInsercionActionPerformed

    private void btnPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlacaActionPerformed
        // TODO add your handling code here:
        PlacaForm placa = new PlacaForm();
        placa.setVisible(true);
    }//GEN-LAST:event_btnPlacaActionPerformed

    private void btnConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultasActionPerformed
        // TODO add your handling code here:
        ConsultasForm consulta = new ConsultasForm(this, true);
        consulta.setVisible(true);
    }//GEN-LAST:event_btnConsultasActionPerformed

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        // TODO add your handling code here:
        try {
            ReporteForm reporte = new ReporteForm(this, true);
            reporte.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnReporteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultas;
    private javax.swing.JButton btnInsercion;
    private javax.swing.JButton btnLicencias;
    private javax.swing.JButton btnPlaca;
    private javax.swing.JButton btnReporte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
